# Generated by Django 5.1.7 on 2025-03-17 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_alter_course_preview_alter_lesson_preview"),
        ("users", "0002_payments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payments",
            options={"verbose_name": "Оплата", "verbose_name_plural": "Оплата"},
        ),
        migrations.AlterField(
            model_name="payments",
            name="paid_course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paid_course",
                to="materials.course",
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="paid_lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paid_lesson",
                to="materials.lesson",
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="pay_date",
            field=models.DateField(auto_now_add=True, verbose_name="дата оплаты"),
        ),
    ]
