# Generated by Django 5.1.7 on 2025-03-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_customuser_is_staff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
