# Generated by Django 5.1.7 on 2025-03-19 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0007_alter_course_owner_alter_lesson_owner"),
        ("users", "0006_alter_payments_paid_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="paid_course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paid_course",
                to="materials.course",
            ),
        ),
    ]
