# Generated by Django 5.1.7 on 2025-04-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_payments_paid_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="link",
            field=models.CharField(
                blank=True, default=None, null=True, verbose_name="ссылка для оплаты"
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="session_id",
            field=models.CharField(
                blank=True, default=None, null=True, verbose_name="идентификатор оплаты"
            ),
        ),
    ]
