# Generated by Django 5.1.7 on 2025-04-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_payments_link_payments_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="link",
            field=models.CharField(
                blank=True, null=True, verbose_name="ссылка для оплаты"
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="session_id",
            field=models.CharField(
                blank=True, null=True, verbose_name="идентификатор оплаты"
            ),
        ),
    ]
