# Generated by Django 5.1.7 on 2025-04-09 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0011_course_updated_ad_lesson_updated_ad"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="updated_ad",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="lesson",
            old_name="updated_ad",
            new_name="updated_at",
        ),
    ]
